### ISSUE TITLE
no ssa.jar file

### ISSUE THREAD

**Issue by mccannannamary** [paulbuenau/SSA-Toolbox#1]
Hello, perhaps I'm not understanding the installation well, but there seems to be no ssa.jar executable file in the repository. Has it been removed?

**Comment by jansaputra** [comment]
Dear Anna, I just added the compiled packages in the root folder for convenience. Inside of them, you will also find the ssa.jar (see the .zip/.tar.gz file). Hope that solves your issue!

**Comment by mccannannamary** [comment]
Dear Jan, thank you so much, yes that solved my issue!
